CREATE TABLE grabli_schema.users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar UNIQUE NOT NULL,
    password varchar        NOT NULL
);

CREATE TABLE grabli_schema.street_object_type
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    tag  varchar NOT NULL
);

CREATE TABLE grabli_schema.street_object
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id         int REFERENCES grabli_schema.street_object_type (id) NOT NULL,
    location        geometry(point, 4326)                                NOT NULL,
    title           varchar                                              NOT NULL,
    description     varchar                                              NOT NULL,
    image           varchar UNIQUE                                       NOT NULL,
    creator_name    varchar                                              NOT NULL,
    creator_contact varchar                                              NOT NULL,
    approved        boolean
);

INSERT INTO grabli_schema.street_object_type (name, tag)
VALUES ('Библиотеки, музеи, научно-технические комплексы', 'library'),
       ('Истории людей', 'story'),
       ('Жизнь молодых учёных', 'science'),
       ('Места получения знаний', 'knowledge');