CREATE TABLE grabli_schema.users
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    varchar NOT NULL,
    password varchar NOT NULL
);

CREATE TABLE grabli_schema.street_object_type
(
    id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar NOT NULL,
    tag  varchar NOT NULL
);

CREATE TABLE grabli_schema.street_object
(
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id         int REFERENCES grabli_schema.street_object_type (id) NOT NULL,
    coordinate      geography(point, 4326) NOT NULL,
    title           varchar NOT NULL,
    description     varchar,
    image           varchar NOT NULL,
    creator_name    varchar NOT NULL,
    creator_contact varchar NOT NULL
);
